import glob
import json
import os
import platform
import shutil
import stat
import subprocess
import sys
import tempfile
import textwrap
import time

BASE_URL = "https://support.eiresystems.com/ticket"
SESSION = "halo"


def find_playwright_cli():
    """
    Find playwright-cli without hard-coding the Windows username.
    """
    cli = shutil.which("playwright-cli")
    if cli:
        return cli

    cli = shutil.which("playwright-cli.cmd")
    if cli:
        return cli

    raise FileNotFoundError("playwright-cli was not found in PATH.")


CLI = find_playwright_cli()


def run_cli(*args, check=True):
    """
    Run playwright-cli safely across platforms.
    """
    if platform.system() == "Windows":
        quoted_args = []
        for arg in args:
            s = str(arg)
            if not (s.startswith('"') and s.endswith('"')):
                s = f'"{s}"'
            quoted_args.append(s)

        cmd_str = f'"{CLI}" "--s={SESSION}" ' + " ".join(quoted_args)

        print()
        print("> " + cmd_str)

        result = subprocess.run(
            cmd_str,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=True,
        )
    else:
        command = [CLI, f"--s={SESSION}", *[str(arg) for arg in args]]

        print()
        print("> " + " ".join(command))

        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            shell=False,
        )

    if result.stdout:
        print(result.stdout)

    if check and result.returncode != 0:
        raise RuntimeError(
            f"Playwright CLI command failed with exit code {result.returncode}"
        )

    return result.stdout


def remove_readonly(func, path, excinfo):
    """
    Error handler for shutil.rmtree to clear read-only bits and retry on Windows.
    """
    os.chmod(path, stat.S_IWRITE)
    func(path)


def cleanup_local_artifacts():
    """
    Remove local .playwright or session folders created in the working directory.
    """
    folders_to_remove = [".playwright", ".playwright-cli"]
    
    for folder in folders_to_remove:
        if os.path.exists(folder) and os.path.isdir(folder):
            try:
                # Close any open file handles to log files first if tracked
                shutil.rmtree(folder, onerror=remove_readonly)
                print(f"Cleaned up local folder: {folder}")
            except Exception as e:
                print(f"Note: Could not fully remove folder {folder}: {e}")


def attach():
    """
    Attach the CLI session to the already-open Microsoft Edge tab
    through the Playwright browser extension.
    """
    print("Attaching to Microsoft Edge...")
    run_cli(
        "attach",
        "--extension=msedge",
    )
    time.sleep(1)


def get_latest_console_log():
    """
    Reads the most recent console log file generated by playwright-cli.
    """
    log_files = glob.glob(os.path.join(".playwright-cli", "console-*.log"))
    if not log_files:
        return ""
    latest_file = max(log_files, key=os.path.getmtime)
    try:
        with open(latest_file, "r", encoding="utf-8") as f:
            return f.read()
    except Exception:
        return ""


def get_ticket_number():
    """
    Allows the user to choose between fetching assigned/recent tickets from the browser
    or typing a ticket number manually.
    """
    print("\n--- Ticket Selection Method ---")
    print("[1] Fetch recent/assigned tickets from Halo view")
    print("[2] Type ticket number manually")
    method = input("Select option [1 or 2]: ").strip()

    if method == "2":
        manual_id = input("Enter ticket number manually: ").strip()
        return manual_id

    print("\nFetching your tickets from HaloPSA...")
    
    js_code = textwrap.dedent(
        """
        async page => {
            await page.goto("https://support.eiresystems.com/tickets?showalltickettypes=1");
            await page.waitForTimeout(3000);

            const tickets = await page.evaluate(() => {
                const results = [];
                const links = document.querySelectorAll('a[href*="ticket?id="]');
                links.forEach(link => {
                    const href = link.getAttribute('href');
                    const match = href.match(/id=(\\d+)/);
                    if (match) {
                        const id = match[1];
                        let title = link.innerText.trim();
                        if (!title) {
                            title = link.getAttribute('aria-label') || link.title || ("Ticket #" + id);
                        }
                        if (!results.some(r => r.id === id)) {
                            results.push({ id: id, title: title });
                        }
                    }
                });
                return results.slice(0, 15);
            });

            console.log("FETCHED_TICKETS_JSON:" + JSON.stringify(tickets));
        }
        """
    )

    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".js", prefix="halo_fetch_", delete=False, encoding="utf-8"
        ) as temp_file:
            temp_file.write(js_code)
            temp_path = temp_file.name

        run_cli("run-code", f"--filename={temp_path}")
        
        console_output = get_latest_console_log()

        tickets = []
        for line in console_output.splitlines():
            if "FETCHED_TICKETS_JSON:" in line:
                try:
                    json_str = line.split("FETCHED_TICKETS_JSON:")[1].strip()
                    tickets = json.loads(json_str)
                    break
                except json.JSONDecodeError:
                    continue

        if not tickets:
            print("\nCould not automatically fetch tickets from the page view.")
            return input("Enter ticket number manually: ").strip()

        print("\n--- Available Tickets ---")
        for idx, t in enumerate(tickets, 1):
            print(f"[{idx}] ID: {t['id']} - {t['title'][:60]}")
        print("[0] Type custom ticket ID manually")
        print("-------------------------")

        choice = input("Select a ticket number from the list (or 0 for manual): ").strip()
        
        if choice.isdigit():
            c_int = int(choice)
            if 1 <= c_int <= len(tickets):
                selected_id = tickets[c_int - 1]['id']
                print(f"Selected Ticket: {selected_id}")
                return selected_id

        return input("Enter ticket number manually: ").strip()

    finally:
        if temp_path and os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except OSError:
                pass


def goto_ticket(ticket):
    """
    Navigate to the requested Halo ticket.
    """
    url = f"{BASE_URL}?id={ticket}&showalltickettypes=1"

    print(f"\nOpening ticket {ticket}...")
    run_cli("goto", url)
    time.sleep(1)


def run_halo_automation(worklog_text, status, start_time, end_time, charge_type):
    """
    Run the actual HaloPSA Worklog automation using Playwright code.
    """
    start_fill_code = f'await allInputs.nth(timeInputIndexes[0]).fill({start_time!r});' if start_time else '// Start time left unchanged'
    end_fill_code = f'await allInputs.nth(timeInputIndexes[1]).fill({end_time!r});' if end_time else '// End time left unchanged'

    js_code = textwrap.dedent(
        f"""
        async page => {{

            console.log("Opening Worklog...");

            await page.getByRole("button", {{
                name: "Worklog"
            }}).click();

            await page.waitForTimeout(1500);

            // ---------------------------------------------------------
            // WORKLOG TEXT
            // ---------------------------------------------------------

            console.log("Entering worklog...");

            const editor = page.locator(
                '[contenteditable="true"]'
            ).first();

            await editor.waitFor({{
                state: "visible",
                timeout: 10000
            }});

            await editor.fill(
                {worklog_text!r}
            );

            // ---------------------------------------------------------
            // STATUS
            // ---------------------------------------------------------

            console.log("Setting status: {status}");

            const statusCombobox = page.getByRole(
                "combobox",
                {{ name: "Status *" }}
            );

            await statusCombobox.click();

            await page.getByText(
                {status!r},
                {{ exact: true }}
            ).click();

            // ---------------------------------------------------------
            // JOB START / END TIMES
            // ---------------------------------------------------------

            console.log("Job Start Time input: {start_time if start_time else '(Leave unchanged)'}");
            console.log("Job End Time input: {end_time if end_time else '(Leave unchanged)'}");

            const timeInputIndexes = await page.locator("input").evaluateAll(inputs => {{
                const result = [];
                inputs.forEach((input, index) => {{
                    const value = input.value || "";
                    const type = (input.getAttribute("type") || "text").toLowerCase();
                    const style = window.getComputedStyle(input);
                    
                    if (style.display !== "none" && style.visibility !== "hidden" && (type === "text" || type === "time")) {{
                        if (value.includes(":") && !value.includes("-") && !value.includes("/")) {{
                            result.push(index);
                        }}
                    }}
                }});
                return result;
            }});

            console.log("Time input indices found:", timeInputIndexes);

            if (timeInputIndexes.length < 2) {{
                throw new Error(
                    "Could not find the two Halo Worklog time inputs. Found " + timeInputIndexes.length
                );
            }}

            const allInputs = page.locator("input");

            {start_fill_code}
            {end_fill_code}

            // ---------------------------------------------------------
            // CHARGE TYPE
            // ---------------------------------------------------------

            console.log(
                "Setting charge type: {charge_type}"
            );

            const chargeTypeCombobox = page.getByRole(
                "combobox",
                {{ name: "Charge Type *" }}
            );

            await chargeTypeCombobox.click();

            await page.getByText(
                {charge_type!r},
                {{ exact: true }}
            ).click();

            // ---------------------------------------------------------
            // FINAL CHECK
            // ---------------------------------------------------------

            console.log(
                "Worklog fields populated. Saving..."
            );

            await page.waitForTimeout(500);

            await page.getByRole(
                "button",
                {{ name: "Save", exact: true }}
            ).click();

            await page.waitForTimeout(1500);

            console.log("Worklog saved.");

        }}
        """
    )

    temp_path = None

    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".js",
            prefix="halo_worklog_",
            delete=False,
            encoding="utf-8",
        ) as temp_file:

            temp_file.write(js_code)
            temp_path = temp_file.name

        print("\nRunning Halo automation...")

        run_cli(
            "run-code",
            f"--filename={temp_path}",
        )

    finally:
        if temp_path and os.path.exists(temp_path):
            try:
                os.remove(temp_path)
            except OSError:
                pass


def take_snapshot():
    """
    Take a final snapshot so we can verify the result.
    """
    print("\nTaking final snapshot...")
    run_cli("snapshot")


def main():
    print()
    print("HaloPSA Worklog Automation")
    print("==========================")

    try:
        attach()

        ticket = get_ticket_number()
        if not ticket or not ticket.isdigit():
            print("Invalid ticket number.")
            return

        worklog_text = ""
        while not worklog_text:
            worklog_text = input("Worklog text (Required): ").strip()
            if not worklog_text:
                print("Worklog text cannot be empty.")

        default_status = "Completed (On Hold)"
        status = input(f"Status [{default_status}]: ").strip() or default_status

        start_time = input("Start time [Leave unchanged, e.g. 09:00]: ").strip()
        end_time = input("End time [Leave unchanged, e.g. 10:00]: ").strip()

        default_charge = "Internal work"
        charge_type = input(f"Charge type [{default_charge}]: ").strip() or default_charge

        goto_ticket(ticket)
        run_halo_automation(worklog_text, status, start_time, end_time, charge_type)
        take_snapshot()

        print()
        print("================================")
        print("Worklog automation completed.")
        print("================================")

    except Exception as exc:
        print()
        print("ERROR:")
        print(exc)
        sys.exit(1)

    finally:
        cleanup_local_artifacts()


if __name__ == "__main__":
    main()